name: NightingaleNotes
options:
  bundleIdPrefix: com.nightingale
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  NightingaleNotes:
    type: application
    platform: iOS
    sources:
      - path: NightingaleNotes
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nightingale.notes
        INFOPLIST_KEY_CFBundleDisplayName: "Nightingale Notes"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_PREVIEWS: YES

  NightingaleNotesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: NightingaleNotes
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nightingale.notes.tests
        GENERATE_INFOPLIST_FILE: YES
